stages:
  - build-net
  - build-images

cache:
  paths:
    - src/web/node_modules/

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375

services:
  - docker:18.09.7-dind

build-net:
  stage: build-net
  image: mcr.microsoft.com/dotnet/sdk:6.0-bullseye-slim
  tags:
    - k8s
  script:
    - export PATH="$PATH:/root/.dotnet/tools"
    - dotnet nuget add source "$CI_SERVER_URL/api/v4/projects/2/packages/nuget/index.json" --name cozybus --username gitlab-ci-token --password $CI_JOB_TOKEN --store-password-in-clear-text
    - dotnet restore src/ReactAspBoilerplate.sln
    - dotnet build src/ReactAspBoilerplate.sln -c Release

build-images:
  stage: build-images
  tags:
    - k8s
  image: docker:stable
  before_script:
    - apk add --no-cache docker-compose
    - docker info
  script:
    - echo "Building docker images"
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker-compose build
    - docker tag identity:latest $CI_REGISTRY_IMAGE/identity:latest
    - echo "Pushing docker images to registry"
    - docker push $CI_REGISTRY_IMAGE/identity:latest